config/routes.rb
Rails.application.routes.draw do
  get "log_out" => 'sessions#destroy', as: "log_out"
  get "log_in" => 'sessions#new', as: "log_in"
  get "sign_up" => 'users#new', as: "sign_up"

  root to: "users#new"

  resources :users

  resources :sessions

  resources :friendships
  
  resources :messages

  resources :rooms

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'
  # リクエストを送ったユーザー
  belongs_to :requested_user, class_name: 'User', foreign_key: 'user_id'
  has_one :room, dependent: :destroy

  validates :user_id,
    presence: true,
    uniqueness: { scope: :friend_id }
  validates_presence_of :friend_id
  validates_presence_of :status

  scope :search_for_friendship, lambda { |fields, name|
    conditions = nil
    fields = [fields] if fields.class == Symbol
    fields.each do |field|
      if conditions.nil?
        conditions = arel_table[field].eq(name)
      else
        conditions = conditions.or(arel_table[field].eq(name))
      end
    end
    where(conditions)
  }

  enum status: { pending: 1, accepted: 2 }.freeze

  def self.already_requested?(user, friend)
    user.friendships.where(friend: friend).present?
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  after_create_commit { BroadcastMessageJob.perform_later self }

  belongs_to :sent_user, class_name: 'User', foreign_key: 'user_id'
  belongs_to :room

  validates_presence_of :content
  validates_presence_of :sent_user
  validates_presence_of :room
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :friendship
  has_many :messages

  validates :friendship_id,
    presence: true,
    uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password

  validates_presence_of :password, on: :create
  validates_confirmation_of :password
  validates :email,
    presence: true,
    uniqueness: true
  validates_presence_of :name

  has_many :friends, through: :friendships
  # リクエストを送ったユーザー
  has_many :requested_users, through: :requested_friendships
  has_many :friendships, dependent: :destroy, foreign_key: 'user_id'
  # 自分に送られたリクエスト
  has_many :requested_friendships, class_name: 'Friendship', dependent: :destroy, foreign_key: 'friend_id'
  has_many :messages

  def self.authenticate(email, password)
    user = User.find_by(email: email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def can_request_to?(friend)
    if friendship_with(friend).present?
      false
    else
      true
    end
  end

  def can_accept?(request)
    if self == request.requested_user
      false
    else
      true
    end
  end

  def my_friendships
    Friendship.search_for_friendship([:user_id, :friend_id], self.id)
  end

  def friendship_with(friend)
    my_friendships.find_by(requested_user: friend) || my_friendships.find_by(friend: friend)
  end

  def unaccepted_requests
    self.requested_friendships.where(status: :pending)
  end

  def waiting_requests
    self.friendships.where(status: :pending)
  end

  def self.search(email)
    if email.present?
      User.find_by(email: email)
    end
  end

  private

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :authenticate

  def create
    friend = User.find(params[:friend_id])
    if @request = request_friendship(friend)
      flash[:notice] = 'success!'
    else
      flash[:notice] = 'failure!'
    end
    redirect_to current_user
  end

  def update
    requested_user = User.find(params[:requested_user_id])
    if accept_friendship(requested_user)
      flash[:notice] = '友達になりました。'
    else
      flash[:notice] = '承認に失敗しました'
    end
    redirect_to current_user
  end

  def destroy
    request = current_user.requested_friendships.find_by(user_id: params[:requested_user_id])
    if request.destroy
      flash.now[:notice] = "却下しました"
    else
      flash.now[:notice] = "却下に失敗しました"
    end
    redirect_to current_user
  end

  private

  def request_friendship(friend)
    unless current_user == friend || Friendship.already_requested?(current_user, friend)
      Friendship.transaction do
        Friendship.create(requested_user: current_user, friend: friend, status: 'pending')
      end
    end
  end

  def accept_friendship(requested_user)
    request = current_user.requested_friendships.find_by(requested_user: requested_user)
    if current_user.can_accept?(request)
      Friendship.transaction do
        request.update!(
         accepted_at: Time.now,
         status: 'accepted',
         room: Room.create!(friendship_id: request.id)
        )
      end
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :check_member, only: [:show]
  before_action :authenticate
  
  def index
    @user = current_user
    @rooms = current_user.my_friendships
  end

  def show
    @room = Room.find(params[:id])
    @user = current_user
    @friend = friend(@room)
    @messages = @room.messages
  end

  private

  def friend(room)
    friendship = room.friendship
    friend = friendship.requested_user == current_user ? friendship.friend : friendship.requested_user
    friend
  end

  def check_member
    friendship = Room.find(params[:id]).friendship
    unless current_user.id == friendship.user_id || current_user.id == friendship.friend_id
      redirect_to current_user
    else
      true
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to current_user if current_user
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      log_in(user)
      redirect_to user
    else
      # flash
      render "new"
    end
  end

  def destroy
    log_out
    redirect_to log_in_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate, only: [:show, :destroy]

  def new
    redirect_to current_user if current_user
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @found_user = User.search(params[:search])
    @unaccepted_requests = current_user.unaccepted_requests
    @waiting_requests = current_user.waiting_requests
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      session[:user_id] = nil
      redirect_to sign_up_path
    else
      redirect_to @user
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id].present?
  end

  def logged_in?
    return unless current_user
    current_user.nil?
  end

  def log_out
    session[:user_id] = nil
    @current_user = nil
  end

  def authenticate
    unless current_user.present?
      redirect_to log_in_path
    else
      true
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friendships/index.html.erb
<h1>友達</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/_message.html.erb
<div class='message'>
  <p><%= "#{message.sent_user.name}: #{message.content}" %></p>
</div>

app/views/rooms/index.html.erb
<h1>Rooms#index</h1>
<div class='rooms'>
  <% @rooms.each do |room| %>
    <div class='name'>
      <p><%= link_to room.friend == @user ? room.requested_user.name : room.friend.name, room_path(room), method: 'get' %></p>
    </div>
  <% end %>
</div>
<div class='links'>
  <span><%= link_to 'プロフィール', user_path(@user), method: 'get' %><span>
</div>

app/views/rooms/show.html.erb
<h1>Chat Room</h1>

<div id='messages', data-room_id="<%= @room.id %>">
  <%= render @messages %>
</div>
<br>
<br>
<div class='input'>
  <form>
    <label>投稿:</label><br>
    <input type='text' data-behavior='room_speaker'>
  </form>
</div>
<br>
<div class='links'>
  <%= link_to 'プロフィール', user_path(@user), method: 'get' %>
</div>

app/views/shared_partials/_form.html.erb
<div class="form">
  <div class="name_field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="email_field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="password_field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="password_confirmation_field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <p class="submit"><%= f.submit %></p>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user, url: { action: :create } do |f| %>
  <%= render partial: 'shared_partials/form', locals: { f: f } %>
<% end %>

app/views/users/show.html.erb
<p><%= "#{@user.name}さん、こんにちは" %></p>
<div class="search">
  <%= form_tag user_path, method: 'get' do %>
    <%= label_tag :email %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search" %>
  <% end %>
</div><br>
<div class="search_results">
  <% if @found_user.present? %>
    <span><%= @found_user.name << 'さん' %></span>
    <% if @user.can_request_to?(@found_user) %>
      <span><%= link_to '友達になる', friendships_path(user_id: @user, friend_id: @found_user), method: 'post' %></span>
    <% elsif friendship = @user.friendship_with(@found_user) %>
      <% if friendship.friend == @found_user %>
        <% if friendship.status == 'pending' %>
          <span><%= link_to '承認する', friendship_path(@user, requested_user_id: @found_user.id), method: 'put' %></span>
          <span><%= link_to '却下する', friendship_path(@user, requested_user_id: @found_user.id), method: 'delete' %></span>
        <% elsif friendship.status == 'accepted' %>
          <span>友達</span>
        <% end %>
      <% elsif friendship.requested_user == @user %>
        <% if friendship.status == 'pending' %>
          <span>承認待ち</span>
        <% elsif friendship.status == 'accepted' %>
          <span>友達</span>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div><br>
<div class="waiting_friendship">
  <% unless @waiting_requests.first == nil %>
    <% @waiting_requests.each do |request| %>
      <div class="waiting_requests">
        <span><%= request.friend.name %></span>
        <span>承認待ち</span>
      </div></br>
    <% end %>
  <% end %>
</div>
<div class="requested_friendship">
  <% unless @unaccepted_requests.first == nil %>
    <% @unaccepted_requests.each do |request| %>
      <div class="waiting_requests">
        <span><%= request.requested_user.name %></span>
        <span><%= link_to '承認する', friendship_path(@user, requested_user_id: request.requested_user.id), method: 'put' %></span>
        <span><%= link_to '却下する', friendship_path(@user, requested_user_id: request.requested_user.id), method: 'delete' %></span>
      </div><br>
    <% end %>
  <% end %>
</div>
<div class="link">
  <span><%= link_to "ログアウト", session_path(@user), method: 'delete' %></span>
  <span><%= link_to "友達", rooms_path %>
  <p><%= link_to "退会", user_path(@user), method: 'delete', data: { confirm: "本当に退会しますか？" } %></p>
</div>